---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: 16.04

inputs:
- name: repo

outputs:
- name: output

run:
  path: /bin/bash
  args: ["-c", "repo/ci/tasks/hello-world/task.sh"]
