---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

#inputs:
#- name: project-src

#outputs:
#- name: built-project

run:
  path: repo/ci/tasks/hello-world/task.sh
