---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/proddam/dojo-test

jobs:
- name: job-hello-world
  public: true
  plan:
#  - get: dojo-timer
#    trigger: false
  - get: repo
    trigger: true
  - task: hello-world
    file: repo/ci/tasks/hello-world/task.yml
